version: "3"
services:
     mongodb:
       image: mongo:5.0
       container_name: mongofiberfull
       restart: always
       environment:
          MONGO_INITDB_ROOT_USERNAME: pilput
          MONGO_INITDB_ROOT_PASSWORD: pilput31
       ports:
         - "27017:27017"
       volumes:
         - mongodata:/data/db
       networks:
         - main
  
networks:
  main:
    external: true
    
volumes: 
  mongodata: