version: '3.5'

services:
  golang-mongo:
    container_name: golang-mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: pilput
      MONGO_INITDB_ROOT_PASSWORD: password
